version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: taskpilot_db
    restart: always
    environment:
      POSTGRES_USER: nikhil
      POSTGRES_PASSWORD: taskpilot
      POSTGRES_DB: taskpilot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: